// Generated by CoffeeScript 1.7.1
(function() {
  exports.Server = require("./lib/Server.coffee").Server;

  exports.Messages = require('./lib/Services').Messages;

  exports.CRUD = require('node-acl').CRUD;

}).call(this);
